import cv2

img1 = cv2.imread('wand_spellN1.jpg', cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread('wand_spellN2.jpg', cv2.IMREAD_GRAYSCALE)
img3 = cv2.imread('wand_spellN3.jpg', cv2.IMREAD_GRAYSCALE)
img4 = cv2.imread('wand_spellN4.jpg', cv2.IMREAD_GRAYSCALE)
img5 = cv2.imread('wand_spellN5.jpg', cv2.IMREAD_GRAYSCALE)
img6 = cv2.imread('wand_spellN6.jpg', cv2.IMREAD_GRAYSCALE)
img7 = cv2.imread('wand_spellN7.jpg', cv2.IMREAD_GRAYSCALE)
img8 = cv2.imread('wand_spellN8.jpg', cv2.IMREAD_GRAYSCALE)
img9 = cv2.imread('wand_spellN9.jpg', cv2.IMREAD_GRAYSCALE)
img10 = cv2.imread('wand_spellN10.jpg', cv2.IMREAD_GRAYSCALE)
img11 = cv2.imread('wand_spellN11.jpg', cv2.IMREAD_GRAYSCALE)
img12 = cv2.imread('wand_spellN12.jpg', cv2.IMREAD_GRAYSCALE)
img13 = cv2.imread('wand_spellN13.jpg', cv2.IMREAD_GRAYSCALE)
img14 = cv2.imread('wand_spellN14.jpg', cv2.IMREAD_GRAYSCALE)
img15 = cv2.imread('wand_spellN15.jpg', cv2.IMREAD_GRAYSCALE)
img16 = cv2.imread('wand_spellN16.jpg', cv2.IMREAD_GRAYSCALE)
img17 = cv2.imread('wand_spellN17.jpg', cv2.IMREAD_GRAYSCALE)
img18 = cv2.imread('wand_spellN18.jpg', cv2.IMREAD_GRAYSCALE)
img19 = cv2.imread('wand_spellN19.jpg', cv2.IMREAD_GRAYSCALE)
img20 = cv2.imread('wand_spellN20.jpg', cv2.IMREAD_GRAYSCALE)

im_h = cv2.hconcat([img1,img2,img3,img4,img5,img6,img7,img8,img9,img10,img11,img12,img13,img14,img15,img16,img17,img18,img19,img20])
cv2.imwrite("N.jpg",im_h)